apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: vaultwarden
    repo: https://guerzon.github.io/vaultwarden
    version: 0.34.4
    releaseName: vaultwarden
    namespace: vaultwarden
    valuesFile: values.yaml

resources:
  - ingress.yaml
  - vaultwarden-admin-secret.yaml
