apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 1.0.3
    releaseName: external-secrets
    namespace: external-secrets
    valuesInline:
      installCRDs: true

resources:
  - cluster-secret-store.yaml
  - tailscale-oauth-external-secret.yaml
