apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd/application.yaml
  - dex/application.yaml
  - external-secrets/application.yaml
  - tailscale-operator/application.yaml
  # - nextcloud/application.yaml  # disabled - manifests kept for reference
  - ente/application.yaml

