apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ente
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/hikuohiku/homelab.git
    targetRevision: HEAD
    path: apps/ente

  destination:
    server: https://kubernetes.default.svc
    namespace: ente

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
