apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ente

resources:
  # External Secrets
  - ente-secrets.yaml
  # PostgreSQL
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  # MinIO (Object Storage)
  - minio-pvc.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - minio-setup-job.yaml
  # Museum (Ente Server)
  - museum-config.yaml
  - museum-deployment.yaml
  - museum-service.yaml
  # Ingress
  - ingress.yaml
